In [1]:
import numpy as np

In [2]:
l= [1,2,3,8,28,2,6]

In [3]:
ar = np.array(l)

In [4]:
ar

array([ 1,  2,  3,  8, 28,  2,  6])

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2],[2,6]])

array([[1, 2],
       [2, 6]])

In [7]:
np.asarray(l)

array([ 1,  2,  3,  8, 28,  2,  6])

In [8]:
np.asanyarray(l)

array([ 1,  2,  3,  8, 28,  2,  6])

In [9]:
np.fromfunction(lambda i,j : i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [10]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.ones([2,3,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [12]:
np.ones([6,2,3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [13]:
df=np.random.randn(3,5)

In [14]:
import pandas as pd

In [15]:
pd.DataFrame(df)

0         1         2         3         4
0 -0.692459  1.334647  1.219147 -0.249599 -0.035031
1  0.930859  1.045013  0.607977 -1.387548  0.156935
2 -0.350490  0.405480 -0.167270 -0.923208 -2.525511

In [16]:
df=np.random.rand(3,5)

In [18]:
df

array([[0.74847521, 0.76373141, 0.86512991, 0.3169385 , 0.88575689],
       [0.28857238, 0.78223829, 0.62927455, 0.42083288, 0.28632878],
       [0.10963985, 0.763656  , 0.43369724, 0.60622739, 0.89584051]])

In [19]:
df=np.random.randint(1,110, (5,7))

In [20]:
df

array([[ 39,  66,  48,  11,  44,  73,  64],
       [ 73,  68,  10,  25,  64,  79,  11],
       [ 51,  81,  38,  70,  75,  93,  94],
       [ 34,  78,  88,  61,  24, 105,  11],
       [ 28,  47,   4,   5, 107,  55,  95]])

In [21]:
pd.DataFrame(df)

0   1   2   3    4    5   6
0  39  66  48  11   44   73  64
1  73  68  10  25   64   79  11
2  51  81  38  70   75   93  94
3  34  78  88  61   24  105  11
4  28  47   4   5  107   55  95

In [22]:
df=np.random.randint(1,110, (50,70))

In [23]:
df

array([[ 69, 105,  47, ...,  89,  13,  84],
       [ 13,   5,  77, ...,  38,  90, 100],
       [  2,  77,  85, ...,   4,  21,  14],
       ...,
       [ 56,  54, 107, ...,  13,  33,  25],
       [ 18, 108,  22, ...,  34,  13,  20],
       [ 76,  75,  90, ...,  50,  31,   9]])

In [24]:
pd.DataFrame(df)

0    1    2    3    4    5    6    7    8    9   ...   60   61   62   63  \
0    69  105   47   78   78   20   43   79   21   31  ...   82  109   73   53   
1    13    5   77   63   58   72   99   28   92   86  ...   77   71   36   17   
2     2   77   85   24   76   77   95   27   88   99  ...   28   99   86   28   
3    46   67   45   30    7   33   61   51   46   67  ...  102   95  109  102   
4    94   34    1   46   20   14   59   67   55   15  ...   46   68   86   45   
5    78   68    2   56   37   32   68   49   87   32  ...   17   88   86   25   
6    55   36   53   90   67   22    9   55    8   42  ...   97   52   49    7   
7    28   23    6   74   45   80   95   45   67   82  ...   82   82   94   60   
8    86   22   27   92   29   67  108   24   75   52  ...   37  107    2   69   
9    33    2   88   81   21   70   70   55   50    4  ...   22   42   15   54   
10   27    8   74   58   97   69   74  107  109   20  ...   62   95   98   56   
11   79  107   34   41   26   67   37   20   85   47  ...    9    1   15   75   
12   90    8   65   29   89   83   40    3   27   62  ...   56   20   25   18   
13   60   88   30   37   24   90   65   69   35  106  ...   30   39   46   83   
14   66   20   20   39  102  107   79   64    8   28  ...   34    1  106   71   
15    8   67   11   92  104   26   62    5   68   84  ...   91   70   61   31   
16   34    2   23   85   71   73   45   67   55   17  ...   49    9   95   35   
17   31   27   58   97   32   32   62   23   39   51  ...   12   18    9   24   
18   13   71   89  107   97   23   71    3   79   52  ...   89   85   27   80   
19   89    7   92   60   17   68   40   73  105   82  ...   89   49   70   23   
20   69   49   80  101   57   77   24    9   88   32  ...   36    9   21   22   
21    9    1   77   84    9   58   16  105   73   30  ...  101   11  105   75   
22    9    2   67   49  102   67   43    9  105   22  ...    7   41    7  103   
23   96   21    2   38    5   60   59   42   37   85  ...  102   38  108   87   
24  102    1   11   94   45   93   97   60   58   77  ...   60   91    3   90   
25   35   71   34   96  106   38   98    9   44   57  ...   33   10   34   62   
26   48   54  100   54   55   33   43   56   31   28  ...   11   46   46   89   
27   47   55  101   86    6   30   97   66  102   26  ...  105   19   71   52   
28   37   26   48    2   86   50   25   23   67   43  ...   91  103   61   14   
29   34   54   20  103   16   10   46   19   87   69  ...  106    1   77   51   
30   90   48   49   31   57  100   84   73   73   34  ...   39   85   49   50   
31   73  103   32  101   43   60   62   11   63   18  ...  100   21   71   65   
32  104  105   16   62   23   12  104  108   39   95  ...  103   19   52  107   
33   39   53   16  103   13   36   49   71   15   46  ...   57   22   11  107   
34   27   40   59   41   73   38   48   79   35   92  ...   92   22   17   81   
35   13   88   80    8   78   11   31   71   53   86  ...   42   75   12   15   
36   54   93   36    9   84   83    3    1   37   23  ...   44   81  106   91   
37   93   90   52   33   59   51   45    9   37   15  ...   57   87   56    3   
38  105   74   42   87   29  106   53   26   86   49  ...   18   66   22   55   
39  105   94   74   27   52   31   50   35    5   90  ...   16   99   36   69   
40   56   83   22   66   47  103   54   25   40   61  ...   49   31    4   19   
41   71    6   72   49   20   96  108   97   31   62  ...   75   84   38   70   
42   57  108   41   40   13   16   69   27  101   72  ...   77   27   22   81   
43   10   21   57    8   22   76   96   89    4    2  ...   10   85   43   22   
44   98   49   91   14   23  108   41   45   73   40  ...   82   74   50   88   
45   54   95   15   68    8   88  101   78   14   33  ...   26   72   66   35   
46   42   14   14   92    6   69   17   87   53   11  ...   31   43   76   61   
47   56   54  107    2  108    8    8   12   33   74  ...   35   36   41   39   
48   18  108   22   96   93   28  10

In [25]:
pd.DataFrame(df).to_csv("Test.csv")

In [29]:
a = np.random.rand(5,6)

In [31]:
np.reshape(a, (6,5))

array([[0.45174828, 0.46765776, 0.95642847, 0.25977307, 0.69874961],
       [0.29428847, 0.82796322, 0.07396379, 0.7321575 , 0.47009588],
       [0.0641453 , 0.22356352, 0.45648022, 0.29830301, 0.00477036],
       [0.22081914, 0.75204058, 0.00938622, 0.7056547 , 0.434743  ],
       [0.82592887, 0.72487747, 0.77691682, 0.28783213, 0.87440973],
       [0.13818737, 0.66912911, 0.57941952, 0.06438102, 0.36463416]])

In [32]:
a

array([[0.45174828, 0.46765776, 0.95642847, 0.25977307, 0.69874961,
        0.29428847],
       [0.82796322, 0.07396379, 0.7321575 , 0.47009588, 0.0641453 ,
        0.22356352],
       [0.45648022, 0.29830301, 0.00477036, 0.22081914, 0.75204058,
        0.00938622],
       [0.7056547 , 0.434743  , 0.82592887, 0.72487747, 0.77691682,
        0.28783213],
       [0.87440973, 0.13818737, 0.66912911, 0.57941952, 0.06438102,
        0.36463416]])

In [34]:
a[2][3]

0.22081914308258666